project/auth.py
#Importamos los módulos a usar de flask
from flask import Blueprint, render_template, redirect, url_for, request, flash
#Importamos los módulos de seguridad para las funciones hash
from werkzeug.security import generate_password_hash, check_password_hash

#Importamos el método login_required de flask_security
from flask_security import login_required
#Importamos los métodos login_user, logout_user flask_security.utils
#########################################################################################
from flask_security.utils import login_user, logout_user, hash_password, encrypt_password
##########################################################################################
#Importamos el modelo del usuario
from . models import User, Role
#Importamos el objeto de la BD y userDataStore desde __init__
from . import db, userDataStore

#Creamos el BluePrint y establecemos que todas estas rutas deben estar dentro de /security para sobre escribir 
# las vistas por omisión de flask-security.
# Por lo que ahora las rutas deberán ser /security/login y security/register
auth = Blueprint('auth', __name__, url_prefix='/security')

@auth.route('/login')
def login():
    return render_template('/security/login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    #Consultamos si existe un usuario ya registrado con el email.
    user = User.query.filter_by(email=email).first()

    #Verificamos si el usuario existe
    #Tomamos el password proporcionado por el usuario lo hasheamos, y lo comparamos con el password de la base de datos.
    if not user or not check_password_hash(user.password, password):
    #if not user or not user.password==encrypt_password(password):
        #Si el usuario no existe o no coinciden los passwords
        flash('El usuario y/o la contraseña son incorrectos')
        return redirect(url_for('auth.login')) #Si el usuario no existe o el password es incorrecto regresamos a login
    
    #Si llegamos a este punto sabemos que el usuario tiene datos correctos.
    #Creamos una sessión y logueamos al usuario
    login_user(user, remember=remember)
    return redirect(url_for('main.index'))


@auth.route('/register')
def register():
    return render_template('/security/register.html')

@auth.route('/register', methods=['POST'])
def register_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')
    rol = request.form['rol']
    #Consultamos si existe un usuario ya registrado con el email.
    user = User.query.filter_by(email=email).first()

    if user: #Si se encontró un usuario, redireccionamos de regreso a la página de registro
        flash('El correo electrónico ya existe')
        return redirect(url_for('auth.register'))

    #Creamos un nuevo usuario con los datos del formulario.
    # Hacemos un hash a la contraseña para que no se guarde la versión de texto sin formato
    #new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))
    userDataStore.create_user(
        name=name, email=email, password=generate_password_hash(password, method='sha256')
    )
    #userDataStore.create_user(
        #name=name, email=email, password=encrypt_password(password)
        #)
    #Añadimos el nuevo usuario a la base de datos.
    #db.session.add(new_user)
    db.session.commit()
    #Obtenemos el ultimo registro de usuario
    RecentUser = db.session.query(User).order_by(User.id.desc()).first()
    #Busca el objeto de Rol que coincida con el que se escogió
    rolN = db.session.query(Role).filter_by(id=rol).first()
    
    #Le agregamos el rol al usuario
    userDataStore.add_role_to_user(RecentUser, rolN)
    db.session.commit()
    print("Usuario con rol registrado")
    flash("Te haz registrado, inicia sesión")

    return redirect(url_for('auth.login'))


@auth.route('/logout')
@login_required
def logout():
    #Cerramos la sessión
    logout_user()
    return redirect(url_for('main.index'))

project/bikes/routes.py
from flask import Blueprint, flash, redirect, render_template, request
from flask_security import login_required, current_user
from flask_security.decorators import roles_required, roles_accepted
from .. import db
from ..models import Bike

bikes = Blueprint('bikes',__name__)

@bikes.route("/comprar")
def comprar():
    flash('Esta función esta en desarrollo')
    bikes = Bike.query.all()    
    return render_template('index.html', bikes=bikes)

@bikes.route("/moduloBici")
@login_required
@roles_accepted('vendedor')
def moduloBici():
    bikes = Bike.query.all()
    return render_template('bikes.html', bikes=bikes)

@bikes.route("/insertarBici", methods=['GET', 'POST'])
@login_required
@roles_accepted('vendedor')
def insertarBici():
    if request.method=='POST':
        nombreBici = request.form.get('name')
        descrip = request.form.get('descripcion')
        precio = request.form.get('precio')
        tipo = request.form.get('tipoBici')
        user_id = current_user.get_id()

        newBike = Bike(nombre = nombreBici,
                        descripcion = descrip,
                        precio = precio,
                        tipo = tipo,
                        idUsuario=user_id)
        
        db.session.add(newBike)
        db.session.commit()
        bikes = Bike.query.all()
        return render_template('bikes.html', bikes=bikes)
    
    return render_template('insert-bike.html')

@bikes.route("/update-bike", methods=['GET', 'POST'])
@login_required
@roles_accepted('vendedor')
def updateBike():
    id = request.args.get('id')
    bike = db.session.query(Bike).filter(Bike.id == id).first()

    if request.method=='POST':
        id = request.form.get('idBike')
        modifBike = db.session.query(Bike).filter(Bike.id == id).first()
        modifBike.nombre = request.form.get('name')
        modifBike.descripcion = request.form.get('descripcion')
        modifBike.precio = request.form.get('precio')
        modifBike.tipo = request.form.get('tipoBici')

        db.session.add(modifBike)
        db.session.commit()
        
        return redirect('moduloBici')
    
    return render_template('update-bike.html', idBike = bike.id,
                                               nombreBike=bike.nombre, 
                                               descBike=bike.descripcion,
                                               precioBike=bike.precio,
                                               tipoBike = bike.tipo)

@bikes.route("/delete-bike", methods=['GET', 'POST'])
@login_required
@roles_accepted('vendedor')
def deleteBike():
    id = request.args.get('id')
    bike = db.session.query(Bike).filter(Bike.id == id).first()

    if request.method=='POST':
        id = request.args.get('id')
        bikeD = db.session.query(Bike).filter(Bike.id == id).first()

        db.session.delete(bikeD)
        db.session.commit()
        return redirect('moduloBici')
    
    return render_template('delete-bike.html', bike=bike)

project/main.py
#Importamos la clase Blueprint del módulo flask
from flask import Blueprint, render_template
#Importamos login_required, current_user de flask_security
from flask_security import login_required, current_user
#Importamos el decorador login_required de flask_security
from flask_security.decorators import roles_required, roles_accepted
#Importamos el objeto de la BD desde __init__.py
from . import db
from .models import Bike

main = Blueprint('main',__name__)

#Definimos la ruta a la página principal
@main.route('/')
def index():
    # Para poder realizar una consulta usando SQLAlchemy
    bikes = Bike.query.all()
    return render_template('index.html',
                           bikes = bikes)
    
@main.route('/contacto')
def contacto():
    
    return render_template('contactanos.html')

#Definimos la ruta a la página de perfil
@main.route('/profile')
@login_required
# El usuario tiene que pertenecer a TODOS los roles
# @roles_required('admin')
# El usuario tiene que pertenecer a al menos UNO de los roles
@roles_accepted('admin', 'vendedor')
def profile():
    return render_template('profile.html', name=current_user.name)

project/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BIKEGOGO</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="../static/bootstrap-5.1.3-dist/css/bootstrap.min.css">
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" integrity="sha384-HO/xEfsx0r6JUXU6fxz9mW+DEg1JBlGmH/J6okI+0GZgnveMQL00Rif0JCUbf0X9">-->
    <link rel="stylesheet" href="../static/css/estilo.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
</head>

<body style="background-image: url(../static/img/fondo.jpg); 
            background-repeat: repeat;
            background-size: contain;">
    <section class="hero">
        <div class="hero-head">
            <nav class="navbar is-warning" style="background-color: #000;">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu has-text-light ">
                        <div class="navbar-start">
                            <img src="../static/img/bike-gogo.png" width="200">
                        </div>
                        <div class="navbar-item has-text-light">
                            <h2 style="font-family: Helvetica;">BIKEGOGO</h2><br>
                        </div>
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item has-text-light">
                                Inicio
                            </a>
                            <a href="{{ url_for('main.contacto') }}" class="navbar-item has-text-light">
                                Contacto
                            </a>
                            {% if current_user.is_authenticated and current_user.roles[0].name == 'vendedor' %}
                            <a href="{{ url_for('bikes.moduloBici') }}" class="navbar-item has-text-light">
                                Tus publicaciones
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item has-text-light">
                                Inicia Sesión
                            </a>
                            <a href="{{ url_for('auth.register') }}" class="navbar-item has-text-light">
                                Registrate
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item has-text-light">
                                Cerrar Sesión
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="hero-body">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <h3 class="text-info">>{{ message }}</h3>
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            <div class="container has-text-centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>
    <script src="../static/bootstrap-5.1.3-dist/js/bootstrap.min.js"></script>
</body>

</html>

project/templates/bikes.html
{% extends "base.html" %}

{% block content %}
<center>
<h1 class="title" style="background-color: goldenrod;">Estas son tus publicaciones </h1>
</center>
<br>
<a href="{{ url_for('bikes.insertarBici') }}" class="btn btn-success"> Agregar &plus;</a>
<br><br>
<div id="mi_div" class="row">
  {% for bike in bikes %}
  {% if current_user.is_authenticated %}
  {% if current_user.id == bike.idUsuario %}
  <div class="card" style="width:15rem;">
    {% if bike.tipo == 1 %}
    <img src="../static/img/mountain-bike.png" class="card-img-top" alt="...">
    {% elif bike.tipo == 2 %}
    <img src="../static/img/turism-bike.png" class="card-img-top" alt="...">
    {% elif bike.tipo == 3 %}
    <img src="../static/img/urban-bike.png" class="card-img-top" alt="...">
    {% else %}
    <img src="../static/img/bike-gogo-mini.png" class="card-img-top" alt="...">
    {% endif %}
    <div class="card-body" style="background-color:seashell;">
      <h5 class="card-title h3 text-uppercase"><b>{{bike.nombre}}</b></h5>
      <p class="card-text">{{bike.descripcion}}</p>
      <p class="card-text text-success">$ {{bike.precio}}</p>
      <a href="update-bike?id={{bike.id}}" class="btn btn-warning text-white">Modificar &updownarrow;</a>
      <a href="delete-bike?id={{bike.id}}" class="btn btn-danger text-white">Eliminar </a>
    </div>
  </div>
  {% endif %}
  {% endif %}
  {%endfor%}
</div>

<script>
    var miDiv = document.getElementById("mi_div");
    if(miDiv.innerHTML.trim() == ""){
      miDiv.innerHTML = '<center><h1 class="title text-info col-5" style="background-color:white;">'+
                        'Aun no haz hecho publicaciones </h1></center>'
    }
</script>
{% endblock %}

project/templates/contactanos.html
{% extends "base.html" %}

{% block content%}
<h1 class="title" style="background-color: goldenrod;">Contacto</h1>
<div class="box">
    <div class="box">
        <form action="" method="POST">
            <div class="field">
                <div class="control">
                    <label for="nombre">Nombre:</label>
                    <input type="text" name="nombre" id="nombre" placeholder="Nombre y apellidos" required>
                    <label for="correo">Correo electrónico:</label>
                    <input type="email" name="correo" id="correo" placeholder="alguien@example.com" required>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <label for="asunto">Asunto:</label>
                    <input class="input" type="text" name="asunto" id="asunto" required>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <label for="mensaje">Mensaje:</label>
                    <textarea class="input is-large" type="text" name="mensaje" id="mensaje" rows="5" required></textarea>
                </div>
            </div>
            <button type="submit" class="btn btn-outline-primary">Enviar</button>
        </form>
        <br>
        <p>En BikeGogo nos gusta escuchar tu opinión.</p>
        <p>Dejanos tus datos y nos pondremos en contacto</p>
    </div>
</div>
{% endblock %}

project/templates/delete-bike.html
{% extends "base.html" %}

{% block content%}
<div class="container">
    <form name="sent" action="/delete-bike?id={{bike.id}}" id="form1" method="POST">
        <div class="row control-group">
            <center>
                <div class="form-group col-xs-12 float-label-form-group controls">
                    <h2 class="title" style="background-color: goldenrod;">¿De verdad deseas eliminar este registro?</h2>
                    <br>
                    <center>
                        <div class="card" style="width:15rem;">
                            {% if bike.tipo == 1 %}
                            <img src="../static/img/mountain-bike.png" class="card-img-top" alt="...">
                            {% elif bike.tipo == 2 %}
                            <img src="../static/img/turism-bike.png" class="card-img-top" alt="...">
                            {% elif bike.tipo == 3 %}
                            <img src="../static/img/urban-bike.png" class="card-img-top" alt="...">
                            {% else %}
                            <img src="../static/img/bike-gogo-mini.png" class="card-img-top" alt="...">
                            {% endif %}
                            <div class="card-body" style="background-color:seashell;">
                              <h5 class="card-title h3 text-uppercase"><b>{{bike.nombre}}</b></h5>
                              <p class="card-text">{{bike.descripcion}}</p>
                              <p class="card-text text-success">$ {{bike.precio}}</p>
                            </div>
                          </div>
                    </center>
                </div>
            </center>
        </div>
        <center>
            <input type="submit" class="btn btn-primary" id="eliminar" name="eliminar" value="Sí, eliminar" />
            <a href="moduloBici" class="btn btn-danger">
                No, cancelar
            </a>
        </center>
    </form>
    {% endblock %}

project/templates/index.html
{% extends "base.html" %}

{% block content %}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="../static/img/BIENVENIDA.png" width="520" alt="Imagen 1">
    </div>

    <div class="carousel-item">
      <img src="../static/img/save-planet.png" width="350" alt="Imagen 3">
    </div>

    <div class="carousel-item">
      <img src="../static/img/banner-ofertaspng.png" width="680" alt="Imagen 3">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>

<br>
<div class="row">
  {% for bike in bikes %}
  {% if current_user.is_authenticated %}
  {% if current_user.id != bike.idUsuario %}
  <div class="card" style="width:15rem;">
    {% if bike.tipo == 1 %}
    <img src="../static/img/mountain-bike.png" class="card-img-top" alt="...">
    {% elif bike.tipo == 2 %}
    <img src="../static/img/turism-bike.png" class="card-img-top" alt="...">
    {% elif bike.tipo == 3 %}
    <img src="../static/img/urban-bike.png" class="card-img-top" alt="...">
    {% else %}
    <img src="../static/img/bike-gogo-mini.png" class="card-img-top" alt="...">
    {% endif %}
    <div class="card-body" style="background-color:seashell;">
      <h5 class="card-title h3 text-uppercase"><b>{{bike.nombre}}</b></h5>
      <p class="card-text">{{bike.descripcion}}</p>
      <p class="card-text text-success">$ {{bike.precio}}</p>
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('bikes.comprar') }}" class="btn btn-primary">Comprar</a>
      {% endif %}
      {% if not current_user.is_authenticated %}
      <a href="{{ url_for('auth.login') }}" class="btn btn-outline-primary">
        Inicia sesión para comprar
      </a>
      {% endif %}
    </div>
  </div>
  {% endif %}
  {% else %}
  <div class="card" style="width:15rem;">
    {% if bike.tipo == 1 %}
    <img src="../static/img/mountain-bike.png" class="card-img-top" alt="...">
    {% elif bike.tipo == 2 %}
    <img src="../static/img/turism-bike.png" class="card-img-top" alt="...">
    {% elif bike.tipo == 3 %}
    <img src="../static/img/urban-bike.png" class="card-img-top" alt="...">
    {% else %}
    <img src="../static/img/bike-gogo-mini.png" class="card-img-top" alt="...">
    {% endif %}
    <div class="card-body" style="background-color:seashell;">
      <h5 class="card-title h3 text-uppercase"><b>{{bike.nombre}}</b></h5>
      <p class="card-text">{{bike.descripcion}}</p>
      <p class="card-text text-success">$ {{bike.precio}}</p>
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('bikes.comprar') }}" class="btn btn-primary">Comprar</a>
      {% endif %}
      {% if not current_user.is_authenticated %}
      <a href="{{ url_for('auth.login') }}" class="btn btn-outline-primary">
        Inicia sesión para comprar
      </a>
      {% endif %}
    </div>
  </div>
  {% endif %}
  {%endfor%}
</div>
{% endblock %}

project/templates/insert-bike.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title" style="background-color: goldenrod;">Registrar bicicleta</h3>
    <div class="box">
        <div class="box">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
            {% endwith %}
        <form method="POST" action="/insertarBici">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Nombre de la bicicleta" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <textarea class="input is-large" id="descripcion" name="descripcion" placeholder="Ingresa una descripción"></textarea>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="precio" placeholder="Ingresa el precio en pesos" min="0" step="0.01" required>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <label for="tipoBici" class="h4">Escoge el tipo de bicicleta </label>
                    <select id="tipoBici" name="tipoBici" class="btn btn-primary">
                        <option value="1">Montaña</option>
                        <option value="2">Turismo</option>
                        <option value="3">Urbana</option>
                    </select>
                    
                </div>
            </div>
            <button type="submit" class="button is-block btn-primary is-large is-fullwidth">Registrar Bicicleta</button>
            <a class="button is-block btn-danger is-large is-fullwidth" href="moduloBici">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

project/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Bienvenido, {{ name }}!
</h1>
{% endblock %}

project/templates/update-bike.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title" style="background-color: goldenrod;">Modificar bicicleta</h3>
    <div class="box">
        <div class="box">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
            {% endwith %}
        <form method="POST" action="/update-bike">
            <input type="text" name="idBike" value="{{idBike}}" hidden>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Nombre de la bicicleta" value="{{nombreBike}}" required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <textarea class="input is-large" id="descripcion" name="descripcion" placeholder="Ingresa una descripción" required value="{{descBike}}">{{descBike}}</textarea>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="precio" placeholder="Ingresa el precio en pesos" min="0" step="0.01" required value="{{precioBike}}">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <label for="tipoBici" class="h4">Escoge el tipo de bicicleta </label>
                    <select id="tipoBici" name="tipoBici" class="btn btn-primary" >
                        <option value="1">Montaña</option>
                        <option value="2">Turismo</option>
                        <option value="3">Urbana</option>
                    </select>
                    
                </div>
            </div>
            <button type="submit" class="button is-block btn-primary is-large is-fullwidth">Modificar Bicicleta</button>
            <a class="button is-block btn-danger is-large is-fullwidth" href="moduloBici">Cancelar</a>
        </form>
    </div>
</div>

<script>
    document.getElementById('tipoBici').value="{{tipoBike}}";
</script>
{% endblock %}